[package]
name = "snarkey-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
snarkey-core = { path = "../snarkey-core" }
clap = { version = "4.0", features = ["derive"] }
base64 = "0.13"

[[bin]]
name = "snarkey-cli"
path = "src/main.rs"
